### ISSUE TITLE
Error with grid: sales_order_create_search_grid

### ISSUE THREAD

**Issue by calvinrreed** [magento-hackathon/GridControl#12]
I need to customize "sales_order_create_search_grid" and add a couple of fields however when I attempt to do add a column or remove a column, I get the following error.

```
Property _columns does not exist

Trace:
#0 /home/utahski-stage/public_html/app/code/community/FireGento/GridControl/Model/Processor.php(167): ReflectionClass->getProperty('_columns')
#1 /home/utahski-stage/public_html/app/code/community/FireGento/GridControl/Model/Processor.php(181): FireGento_GridControl_Model_Processor->getReflectedProperty(Object(Mage_Adminhtml_Block_Sales_Order_Create_Items_Grid), '_columns')
#2 /home/utahski-stage/public_html/app/code/community/FireGento/GridControl/Model/Processor.php(214): FireGento_GridControl_Model_Processor->getGridProtectedPropertyValue(Object(Mage_Adminhtml_Block_Sales_Order_Create_Items_Grid), '_columns')
#3 /home/utahski-stage/public_html/app/code/community/FireGento/GridControl/Model/Processor.php(63): FireGento_GridControl_Model_Processor->removeGridColumn(Object(Mage_Adminhtml_Block_Sales_Order_Create_Items_Grid), 'name')
#4 [internal function]: FireGento_GridControl_Model_Processor->_removeAction(Object(Varien_Object))
#5 /home/utahski-stage/public_html/app/code/community/FireGento/GridControl/Model/Processor.php(38): call_user_func(Array, Object(Varien_Object))
#6 /home/utahski-stage/public_html/app/code/community/FireGento/GridControl/Model/Observer.php(24): FireGento_GridControl_Model_Processor->processBlock(Object(Mage_Adminhtml_Block_Sales_Order_Create_Items_Grid))
#7 /home/utahski-stage/public_html/app/code/core/Mage/Core/Model/App.php(1338): FireGento_GridControl_Model_Observer->adminhtmlBlockHtmlBefore(Object(Varien_Event_Observer))
#8 /home/utahski-stage/public_html/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(FireGento_GridControl_Model_Observer), 'adminhtmlBlockH...', Object(Varien_Event_Observer))
#9 /home/utahski-stage/public_html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('adminhtml_block...', Array)
#10 /home/utahski-stage/public_html/app/code/core/Mage/Adminhtml/Block/Template.php(80): Mage::dispatchEvent('adminhtml_block...', Array)
#11 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#12 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#13 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Abstract.php(577): Mage_Core_Block_Abstract->_getChildHtml('items_grid', true)
#14 /home/utahski-stage/public_html/app/design/adminhtml/default/default/template/sales/order/create/items.phtml(32): Mage_Core_Block_Abstract->getChildHtml()
#15 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/utahski-s...')
#16 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#17 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#18 /home/utahski-stage/public_html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#19 /home/utahski-stage/public_html/app/code/core/Mage/Adminhtml/Block/Sales/Order/Create/Items.php(107): Mage_Adminhtml_Block_Template->_toHtml()
#20 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Sales_Order_Create_Items->_toHtml()
#21 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#22 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('items', true)
#23 /home/utahski-stage/public_html/app/design/adminhtml/default/default/template/sales/order/create/data.phtml(47): Mage_Core_Block_Abstract->getChildHtml('items')
#24 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/utahski-s...')
#25 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#26 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#27 /home/utahski-stage/public_html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#28 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#29 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#30 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('data', true)
#31 /home/utahski-stage/public_html/app/design/adminhtml/default/default/template/sales/order/create/form.phtml(45): Mage_Core_Block_Abstract->getChildHtml('data')
#32 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/utahski-s...')
#33 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#34 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#35 /home/utahski-stage/public_html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#36 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#37 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#38 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('form', true)
#39 /home/utahski-stage/public_html/app/code/core/Mage/Adminhtml/Block/Widget/Form/Container.php(130): Mage_Core_Block_Abstract->getChildHtml('form')
#40 /home/utahski-stage/public_html/app/code/core/Mage/Adminhtml/Block/Sales/Order/Create.php(104): Mage_Adminhtml_Block_Widget_Form_Container->getFormHtml()
#41 /home/utahski-stage/public_html/app/design/adminhtml/default/default/template/widget/form/container.phtml(37): Mage_Adminhtml_Block_Sales_Order_Create->getFormHtml()
#42 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/utahski-s...')
#43 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#44 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#45 /home/utahski-stage/public_html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#46 /home/utahski-stage/public_html/app/code/core/Mage/Adminhtml/Block/Widget/Container.php(308): Mage_Adminhtml_Block_Template->_toHtml()
#47 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Widget_Container->_toHtml()
#48 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#49 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#50 /home/utahski-stage/public_html/app/design/adminhtml/default/default/template/page.phtml(74): Mage_Core_Block_Abstract->getChildHtml('content')
#51 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/utahski-s...')
#52 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#53 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#54 /home/utahski-stage/public_html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#55 /home/utahski-stage/public_html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#56 /home/utahski-stage/public_html/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#57 /home/utahski-stage/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#58 /home/utahski-stage/public_html/app/code/core/Mage/Adminhtml/controllers/Sales/Order/CreateController.php(341): Mage_Core_Controller_Varien_Action->renderLayout()
#59 /home/utahski-stage/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Sales_Order_CreateController->indexAction()
#60 /home/utahski-stage/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#61 /home/utahski-stage/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#62 /home/utahski-stage/public_html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#63 /home/utahski-stage/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#64 /home/utahski-stage/public_html/index.php(87): Mage::run('', 'store')
#65 {main}
```

**Comment by Schrank** [comment]
I have no clue how this grid works but it doesn't extend `Mage_Adminhtml_Block_Widget_Grid` therefore this module won't work on this "grid" - and I don't think it can be adjusted to do so.

**Comment by Schrank** [comment]
You want `sales_order_create_search_grid` but the code says you try to change `Mage_Adminhtml_Block_Sales_Order_Create_Items_Grid`. Fix this and it should work.

**Comment by calvinrreed** [comment]
It turns out that both Mage_Adminhtml_Block_Sales_Order_Create_Items_Grid and Mage_Adminhtml_Block_Sales_Order_Create_Search_Grid each have the same grid_id declared in their respective Grid.php file.  (I assumed that each grid_id would be unique).
I was able to override it with a unique grid_id in the local codepool and this stopped the error.

Thanks @Schrank for your assistance.
